{% set python_min = "3.12" %}
{% set name = "seabirdfilehandler" %}
{% set version = "0.11.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/seabirdfilehandler-{{ version }}.tar.gz
  sha256: 15a8aab080a8a6a0d9e5ffe7bf6bd4d721e76c3cf77e46cea6a9fad43df34039

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning >=1.0.0,<2.0.0
    - pip
  run:
    - python >={{ python_min }}
    - pandas >=2.2.1
    - xmltodict >=0.13.0
    - seabirdscientific

test:
  imports:
    - seabirdfilehandler
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://ctd-software.pages.io-warnemuende.de/seabirdfilehandler
  summary: Library of parsers to interact with SeaBird CTD files.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
