{% set python_min = "3.12" %}
{% set name = "seabirdfilehandler" %}
{% set version = "0.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/seabirdfilehandler-{{ version }}.tar.gz
  sha256: 889d82a5704d01a2f5c2ba715c288b9636eab8f3dfcf3a0bb5e53321b6ca0be0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning >=1.0.0,<2.0.0
    - pip
  run:
    - python >={{ python_min }}
    - pandas >=2.2.1
    - xmltodict >=0.13.0

test:
  imports:
    - seabirdfilehandler
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://ctd-software.pages.io-warnemuende.de/seabirdfilehandler
  summary: Library of parsers to interact with SeaBird CTD files.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
